### ISSUE TITLE
大佬 为啥我的自动提交和你的不一样

### ISSUE THREAD

**Issue by Faker0715** [lete114/Hexo-SEO-AutoPush#1]
![image](https://user-images.githubusercontent.com/36560441/122589087-6a2bf380-d092-11eb-873c-27d81fb5f1f9.png)

**Comment by lete114** [comment]
请注意你的博客地址
![image](https://user-images.githubusercontent.com/48512251/122638771-a14ce400-d128-11eb-8b6b-b8d2f3c7c7a0.png)

**Comment by Faker0715** [comment]
噢噢解决了 谢谢大佬 有个问题 我只有百度的action 没有bing的action  这是正常的吗
![image](https://user-images.githubusercontent.com/36560441/122641367-6e5e1c80-d137-11eb-8723-debfb96589aa.png)
最后一个问题 我开了代理 能上google 但是还是提示这个错误
![image](https://user-images.githubusercontent.com/36560441/122641385-a36a6f00-d137-11eb-9656-48b3597a8606.png)

**Comment by lete114** [comment]
> 噢噢解决了 谢谢大佬 有个问题 我只有百度的action 没有bing的action 这是正常的吗
> ![image](https://user-images.githubusercontent.com/36560441/122641367-6e5e1c80-d137-11eb-8723-debfb96589aa.png)

没看懂给是什么意思


> 最后一个问题 我开了代理 能上google 但是还是提示这个错误
> ![image](https://user-images.githubusercontent.com/36560441/122641385-a36a6f00-d137-11eb-9656-48b3597a8606.png)

这个问题没遇到过，貌似 https://www.googleapis.com/oauth2/v4/token 不存在，而且这貌似不是hexo-seo-autopush插件的问题，请合理排除问题(你可以到该路径看看是什么问题)
![image](https://user-images.githubusercontent.com/48512251/122642193-c5fe8700-d13b-11eb-812e-f1959f22dd14.png)

**Comment by Faker0715** [comment]
设置好了 把代理重新弄了弄 就是想问一下 我那个actions只有百度的 是不是少了一个bing的action 我都设置了密钥了 还有就是点那个star 是这个star吗
![image](https://user-images.githubusercontent.com/36560441/122651927-71c0ca80-d16e-11eb-9856-8666f31e2a8b.png)

**Comment by Faker0715** [comment]
没事了大佬 搞明白了...没看见返回的 还有bing的 只看见前面的百度

**Comment by lete114** [comment]
> 设置好了 把代理重新弄了弄 就是想问一下 我那个actions只有百度的 是不是少了一个bing的action 我都设置了密钥了 还有就是点那个star 是这个star吗
> ![image](https://user-images.githubusercontent.com/36560441/122651927-71c0ca80-d16e-11eb-9856-8666f31e2a8b.png)

点击你自己的仓库，star可手动执行

**Comment by Faker0715** [comment]
大佬 这两天action都失败了 不知道咋回事

**Comment by Faker0715** [comment]
![image](https://user-images.githubusercontent.com/36560441/125903279-1dc474d9-cdb6-4eb5-a7d5-8f53d551b594.png)
![image](https://user-images.githubusercontent.com/36560441/125903310-e3015902-9d8e-47b3-8b4f-37dc051c81db.png)
