### ISSUE TITLE
提示node过时了，怎么弄哦

### ISSUE THREAD

**Issue by RockJesus** [Lete114/Hexo-SEO-AutoPush#10]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-node@v1

**Comment by Lete114** [comment]
将插件更新到`2.1.3`版本以上即可
