### ISSUE TITLE
refalsh

### ISSUE THREAD

**Issue by zEpoch** [Lete114/Hexo-SEO-AutoPush#13]
老哥，新的版本的码是不是要更新一下啊，把判定程序改一下吧。

**Comment by zEpoch** [comment]
if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule'

**Comment by Lete114** [comment]
什么意思？没看明白你的意思

**Comment by zEpoch** [comment]
抱歉抱歉，是我太久没更新了，看到你已经更新了就好了
