### ISSUE TITLE
用不了了好像

### ISSUE THREAD

**Issue by g0fcn** [Lete114/Hexo-SEO-AutoPush#14]
[![Hexo SEO Auto Push](https://github.com/g0fcn/blog.g0f.cn/actions/workflows/HexoSeoAutoPush.yml/badge.svg)](https://github.com/g0fcn/blog.g0f.cn/actions/workflows/HexoSeoAutoPush.yml)

**Comment by SaraKale** [comment]
同+1，我这边提示要更新Node.js 20，虽然actions状态正常，但是看站长后台好像没提交成功的样子。
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
