### ISSUE TITLE
cron问题？0 4 0 0 0 不是默认每天12点吧，是否得更改

### ISSUE THREAD

**Issue by magnificent007** [Lete114/Hexo-SEO-AutoPush#2]

**Comment by Lete114** [comment]
1. 是 `0 4 * * *` 不是 `0 4 0 0 0` 
2. GitHub actions 遵循的是UTC时间，并非北京时间，而UTC的4:00换算成北京时间则恰好是中午12:00
3. 如果你想自定义cron时间可以在配置文件内配置cron时间

**Comment by magnificent007** [comment]
> 1. 是 `0 4 * * *` 不是 `0 4 0 0 0`
> 2. GitHub actions 遵循的是UTC时间，并非北京时间，而UTC的4:00换算成北京时间则恰好是中午12:00
> 3. 如果你想自定义cron时间可以在配置文件内配置cron时间

好的谢谢
