### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by Pride-lee** [Lete114/Hexo-SEO-AutoPush#5]
大佬好，请问这是什么问题，好像没读取到token？忽略文件配置我也设置了
![image](https://user-images.githubusercontent.com/84007026/182522697-24b5d5f8-301a-4a25-a285-743d92e61076.png)
![image](https://user-images.githubusercontent.com/84007026/182522737-08842fd8-ca54-46ed-8692-8f4ca153a1d3.png)
![image](https://user-images.githubusercontent.com/84007026/182523033-fa5b7079-ef3a-43a6-bda4-bddb10c8233c.png)

**Comment by Lete114** [comment]
没遇到过这个问题，可能是你token写错了，导致百度服务器那边拒绝了请求，你检查一下token

**Comment by Lete114** [comment]
或者你hexo g之后用命令行进入public目录下复制执行以下命令试试
```bash
curl -H 'Content-Type:text/plain' --data-binary @baidu.txt 'http://data.zz.baidu.com/urls?site=https://lhx.zzux.com&token=这里写你的token'
```

**Comment by Lete114** [comment]
这是我电脑本地执行成功的截图，看来因该是百度的海外节点出现了问题导致无法请求百度的接口照成的，也有可能是百度直接禁止了github action的ip所以导致无法请求百度的接口
![image](https://user-images.githubusercontent.com/48512251/183009128-d5f00e11-6ff7-473c-a761-32adaddc2611.png)

**Comment by Lete114** [comment]
你点击一下你仓库的star，可以触发actions执行，5秒后再点击一次取消，这时你看看你的action是否执行成功

这时我今天执行失败的action: https://github.com/Lete114/lete114.github.io/actions/runs/2801352423

于是我点击star让action再次执行一遍后就成功了: https://github.com/Lete114/lete114.github.io/actions/runs/2801495791

**Comment by Pride-lee** [comment]
感谢回复啦，我action试了好多次都不行，错误代码都是56，不搞了，反正也不收录
