### ISSUE TITLE
最近action运行失败，出现 "This job was skipped"

### ISSUE THREAD

**Issue by appotry** [Lete114/Hexo-SEO-AutoPush#6]
前段时间一直工作良好，不知道什么原因造成的

https://github.com/appotry/hexo/actions

**Comment by appotry** [comment]
cron 运行失败，但是stared 运行还是可用的，难道被github屏蔽了？

**Comment by Lete114** [comment]
更新插件到最新版因该就能解决了

**Comment by appotry** [comment]
感谢回复，升级测试一下

**Comment by appotry** [comment]
https://github.com/appotry/hexo/actions/runs/3224458968

还是不行，同样的错误

**Comment by Lete114** [comment]
为什么你的没有执行，而是中断

**Comment by Lete114** [comment]
好奇怪，我的也一样，可能是github的问题，我有空看一下

**Comment by appotry** [comment]
https://github.com/appotry/hexo/issues/3

[Update actions/setup-node action to v3](https://github.com/appotry/hexo/pull/2)

[renovate](https://github.com/apps/renovate) 提示，这个action可以升级到v3

**Comment by appotry** [comment]
if: github.event.repository.owner.id == github.event.sender.id
这一行屏蔽了，cron就可用了，应该是这个条件判断有误

**Comment by Lete114** [comment]
确实是这条判断的问题，我昨天已经把if判断删了，今天中午我的已执行成功


https://github.com/Lete114/lete114.github.io/actions


在今天晚上7点我会对插件进行修改，并发布新版本，你只需要在今晚7点后更新插件即可
