### ISSUE TITLE
定时提交会出现Skipped的情况

### ISSUE THREAD

**Issue by czhlin** [Lete114/Hexo-SEO-AutoPush#8]
![image](https://user-images.githubusercontent.com/56159557/196610413-3d4fb467-2461-4494-81d4-c36ce6d5e56b.png)
![image](https://user-images.githubusercontent.com/56159557/196610520-a45d3170-0b62-49ef-bc3d-92439afa4254.png)
定时提交会出现Skipped的情况，手动star触发是成功的。

**Comment by Lete114** [comment]
请将插件升级到最新版，具体问题 #6
