### ISSUE TITLE
NPM还是2.1.1版本

### ISSUE THREAD

**Issue by flow2000** [Lete114/Hexo-SEO-AutoPush#9]
![image](https://user-images.githubusercontent.com/67251012/197382829-ebcab80a-e98e-44c1-a725-9402d5343c3e.png)
![image](https://user-images.githubusercontent.com/67251012/197382903-94ad8ea8-94fc-4eb3-acac-d88569804456.png)
![image](https://user-images.githubusercontent.com/67251012/197382936-9b4c3aaf-d730-49f8-a7f5-b1ca1cf5f3b2.png)

如题，我在package.json改成2.1.2或者2.1.3，npm/cnpm提示我找不到这个包，但是我看master已经到2.1.3了，tags/releases没有到2.1.3

**Comment by Lete114** [comment]
用npm
